import Link from 'next/link'
import { Card, Container } from 'react-bootstrap'

export default function AboutUsPage() {
  return (<>
    <Container fluid="sm">
      <br />
      <Card >
        <Card.Header >About project</Card.Header>
        <Card.Body>
          &quotBook chart&quot is the website to visually compare the total number of pages in different book series. For example, compare how much &quotThe Lord of Rings&quot series is bigger than &quotThe Dune&quot. Website is generated by Next.js - generator of static websites that takes raw JSON data and generates a comparison chart.
        </Card.Body>
      </Card>
      <br />
      <Card  >
        <Card.Header >Source code</Card.Header>
        <Card.Body>
          <Link href="https://github.com/Ostehura/books-chart">GitHub</Link>
        </Card.Body>
      </Card>

    </Container>

  </>)
}